// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomRental.Infrastructure.Data;

#nullable disable

namespace RoomRental.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoomRental.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("MoTa");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("TrangThai");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTienNghi");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TienNghi", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.BlogComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanId");

                    b.Property<int>("BlogPostId")
                        .HasColumnType("int")
                        .HasColumnName("BaiVietId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("NoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BlogPostId");

                    b.ToTable("BinhLuan", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorAccountId")
                        .HasColumnType("int")
                        .HasColumnName("TacGiaId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayDang");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("Slug");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TrangThai");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("TomTat");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("TieuDe");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int")
                        .HasColumnName("LuotXem");

                    b.HasKey("Id");

                    b.HasIndex("AuthorAccountId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BaiViet", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayLuu")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("TinDangId");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("TenantId", "PostId")
                        .IsUnique();

                    b.ToTable("YeuThich", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.LandlordProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanId");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("CitizenId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SoCanCuoc");

                    b.Property<string>("Introduction")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GioiThieu");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("DaXacThuc");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayXacThuc");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("CitizenId")
                        .IsUnique()
                        .HasFilter("[SoCanCuoc] IS NOT NULL");

                    b.ToTable("ChuTro", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("NoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("DaDoc");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LienKet");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TieuDe");

                    b.Property<int?>("Type")
                        .HasColumnType("int")
                        .HasColumnName("LoaiThongBao");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayDuyet");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<decimal>("DisplayPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiaHienThi");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayHetHan");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int")
                        .HasColumnName("ChuTroId");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayDang");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LyDoTuChoi");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("PhongTroId");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TrangThai");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("TieuDe");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int")
                        .HasColumnName("LuotXem");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId");

                    b.HasIndex("RoomId");

                    b.HasIndex("Status");

                    b.ToTable("TinDang", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.PostAmenity", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("PhongTroId");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int")
                        .HasColumnName("TienNghiId");

                    b.HasKey("RoomId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("PhongTro_TienNghi", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.PostImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ThuTu");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DuongDan");

                    b.Property<bool>("IsThumbnail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("LaAnhDaiDien");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("PhongTroId");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("RoomId");

                    b.ToTable("HinhAnhPhong", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayBaoCao")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("MoTa");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("TinDangId");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LyDo");

                    b.Property<int>("ReporterAccountId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiBaoCaoId");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayXuLy");

                    b.Property<int?>("ResolvedByAccountId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiXuLyId");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("ReporterAccountId");

                    b.HasIndex("ResolvedByAccountId");

                    b.ToTable("BaoCaoTinDang", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("__UnusedRoles", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DiaChi");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("DienTich");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("int")
                        .HasColumnName("SoPhongTam");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("int")
                        .HasColumnName("SoPhongNgu");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("DanhMucId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("CurrentOccupants")
                        .HasColumnType("int")
                        .HasColumnName("SoNguoiHienTai");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("QuanHuyen");

                    b.Property<decimal?>("ElectricityPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TienDien");

                    b.Property<int?>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("Tang");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int")
                        .HasColumnName("ChuTroId");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("ViDo");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("KinhDo");

                    b.Property<int>("MaxOccupants")
                        .HasColumnType("int")
                        .HasColumnName("SoNguoiToiDa");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiaThue");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TinhThanh");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenPhong");

                    b.Property<decimal?>("ServiceFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PhiDichVu");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PhuongXa");

                    b.Property<decimal?>("WaterPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TienNuoc");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("District");

                    b.HasIndex("LandlordId");

                    b.HasIndex("Province");

                    b.HasIndex("Status");

                    b.ToTable("PhongTro", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.RoomCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MoTa");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("TrangThai");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenDanhMuc");

                    b.HasKey("Id");

                    b.ToTable("DanhMucPhong", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.TenantProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanId");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("CurrentAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DiaChiHienTai");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("Introduction")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GioiThieu");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NgheNghiep");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("HoTen");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("TrangThai");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MatKhauHash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SoDienThoai");

                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("VaiTro");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenDangNhap");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.ViewingAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int")
                        .HasColumnName("ChuTroId");

                    b.Property<string>("LandlordResponse")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LyDoTuChoi");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("TinDangId");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianHen");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TrangThai");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.Property<string>("TenantNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("NoiDung");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId");

                    b.HasIndex("PostId");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("LichHenXemPhong", (string)null);
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.BlogComment", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.User", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoomRental.Domain.Entities.BlogPost", "BlogPost")
                        .WithMany("Comments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.BlogPost", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.Post", "Post")
                        .WithMany("Favorites")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoomRental.Domain.Entities.TenantProfile", "Tenant")
                        .WithMany("Favorites")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.LandlordProfile", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.User", "Account")
                        .WithOne("LandlordProfile")
                        .HasForeignKey("RoomRental.Domain.Entities.LandlordProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Notification", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.User", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Post", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.LandlordProfile", "Landlord")
                        .WithMany("Posts")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoomRental.Domain.Entities.Room", "Room")
                        .WithMany("Posts")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Landlord");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.PostAmenity", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.Amenity", "Amenity")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoomRental.Domain.Entities.Room", "Room")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.PostImage", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Report", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.Post", "Post")
                        .WithMany("Reports")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoomRental.Domain.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoomRental.Domain.Entities.User", "ResolvedBy")
                        .WithMany()
                        .HasForeignKey("ResolvedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Post");

                    b.Navigation("Reporter");

                    b.Navigation("ResolvedBy");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Room", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.RoomCategory", "Category")
                        .WithMany("Rooms")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoomRental.Domain.Entities.LandlordProfile", "Landlord")
                        .WithMany("Rooms")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.TenantProfile", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.User", "Account")
                        .WithOne("TenantProfile")
                        .HasForeignKey("RoomRental.Domain.Entities.TenantProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.ViewingAppointment", b =>
                {
                    b.HasOne("RoomRental.Domain.Entities.LandlordProfile", "Landlord")
                        .WithMany("Appointments")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoomRental.Domain.Entities.Post", "Post")
                        .WithMany("Appointments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoomRental.Domain.Entities.TenantProfile", "Tenant")
                        .WithMany("Appointments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Landlord");

                    b.Navigation("Post");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Amenity", b =>
                {
                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.BlogPost", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.LandlordProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Posts");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Post", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Favorites");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.Room", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Posts");

                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.RoomCategory", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.TenantProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("RoomRental.Domain.Entities.User", b =>
                {
                    b.Navigation("LandlordProfile");

                    b.Navigation("TenantProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
