import React, { useEffect, useMemo, useState } from 'react';
import { FiCheck, FiCheckCircle, FiClock, FiMapPin, FiPhone, FiUser, FiX } from 'react-icons/fi';
import { toast } from 'react-toastify';
import StatusBadge, { StatusTone } from '../../components/common/StatusBadge';
import PageState from '../../components/common/PageState';
import { AppointmentItem } from '../../services/appointmentService';
import { landlordService } from '../../services/landlordService';
import { APPOINTMENT_STATUS, APPOINTMENT_STATUS_LABELS } from '../../utils/constants';
import { getApiErrorMessage } from '../../utils/apiError';

const tone = (status: number): StatusTone => status === 0 ? 'pending' : status === 1 ? 'success' : status === 3 ? 'info' : 'danger';

const LandlordAppointmentsPage: React.FC = () => {
  const [items,setItems]=useState<AppointmentItem[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [filter,setFilter]=useState<number|'all'>('all');
  const load=async()=>{setLoading(true);setError('');try{const r=await landlordService.getAppointments();const d=r?.data||r||[];setItems(Array.isArray(d)?d:[]);}catch(e){const m=getApiErrorMessage(e,'Không thể tải lịch hẹn.');setError(m);toast.error(m);}finally{setLoading(false);}};
  useEffect(()=>{void Promise.resolve().then(load);},[]);
  const visible=useMemo(()=>filter==='all'?items:items.filter(x=>x.status===filter),[items,filter]);
  const act=async(id:number,action:'confirm'|'reject'|'complete')=>{try{if(action==='confirm')await landlordService.confirmAppointment(id);if(action==='complete')await landlordService.completeAppointment(id);if(action==='reject'){const reason=window.prompt('Nhập lý do từ chối lịch hẹn:');if(reason===null)return;await landlordService.rejectAppointment(id,reason.trim()||undefined);}toast.success('Đã cập nhật lịch hẹn');await load();}catch(e){toast.error(getApiErrorMessage(e,'Không thể cập nhật lịch hẹn.'));}};
  return <div className="mx-auto max-w-6xl p-4 md:p-6"><header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase text-blue-600">Chủ trọ</p><h1 className="text-2xl font-bold text-slate-900">Lịch xem phòng</h1><p className="mt-1 text-sm text-slate-500">Duyệt và theo dõi các buổi xem phòng.</p></div><select value={filter} onChange={e=>setFilter(e.target.value==='all'?'all':Number(e.target.value))} className="rounded-md border border-slate-300 bg-white px-3 py-2 text-sm"><option value="all">Tất cả trạng thái</option>{Object.entries(APPOINTMENT_STATUS_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></header>
  {loading?<PageState type="loading" message="Đang tải lịch hẹn..."/>:error?<PageState type="error" message={error} onRetry={load}/>:visible.length===0?<PageState type="empty" message="Chưa có lịch xem phòng phù hợp."/>:<div className="space-y-3">{visible.map(a=><article key={a.id} className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:justify-between"><div className="min-w-0"><div className="mb-3 flex flex-wrap items-center gap-2"><h2 className="text-lg font-bold">{a.roomName||a.postTitle}</h2><StatusBadge label={APPOINTMENT_STATUS_LABELS[a.status as keyof typeof APPOINTMENT_STATUS_LABELS]||'Không xác định'} tone={tone(a.status)}/></div><div className="grid gap-2 text-sm text-slate-600 sm:grid-cols-2"><span className="flex gap-2"><FiMapPin/>{a.postAddress}</span><span className="flex gap-2"><FiClock/>{new Date(a.scheduledAt).toLocaleString('vi-VN')}</span><span className="flex gap-2"><FiUser/>{a.tenantName}</span><span className="flex gap-2"><FiPhone/>{a.tenantPhone}</span></div>{a.tenantNote&&<p className="mt-3 rounded-md bg-slate-50 p-3 text-sm">Ghi chú: {a.tenantNote}</p>}</div><div className="flex flex-wrap items-start gap-2">{a.status===APPOINTMENT_STATUS.PENDING&&<><button onClick={()=>act(a.id,'confirm')} className="inline-flex items-center gap-2 rounded-md bg-emerald-600 px-3 py-2 text-sm font-semibold text-white"><FiCheck/>Chấp nhận</button><button onClick={()=>act(a.id,'reject')} className="inline-flex items-center gap-2 rounded-md border border-rose-200 px-3 py-2 text-sm font-semibold text-rose-700"><FiX/>Từ chối</button></>}{a.status===APPOINTMENT_STATUS.CONFIRMED&&<button onClick={()=>act(a.id,'complete')} className="inline-flex items-center gap-2 rounded-md bg-blue-600 px-3 py-2 text-sm font-semibold text-white"><FiCheckCircle/>Hoàn thành</button>}</div></div></article>)}</div>}</div>;
};
export default LandlordAppointmentsPage;
